<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260112162142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE friend_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, requester_id INT NOT NULL, receiver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F284D94ED442CF4 ON friend_request (requester_id)');
        $this->addSql('CREATE INDEX IDX_F284D94CD53EDB6 ON friend_request (receiver_id)');
        $this->addSql('CREATE TABLE gift (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, image_url VARCHAR(500) DEFAULT NULL, priority INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A47C990D7E3C61F9 ON gift (owner_id)');
        $this->addSql('CREATE TABLE gift_user (gift_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (gift_id, user_id))');
        $this->addSql('CREATE INDEX IDX_7FEE241497A95A83 ON gift_user (gift_id)');
        $this->addSql('CREATE INDEX IDX_7FEE2414A76ED395 ON gift_user (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE friend_request ADD CONSTRAINT FK_F284D94ED442CF4 FOREIGN KEY (requester_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE friend_request ADD CONSTRAINT FK_F284D94CD53EDB6 FOREIGN KEY (receiver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gift ADD CONSTRAINT FK_A47C990D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gift_user ADD CONSTRAINT FK_7FEE241497A95A83 FOREIGN KEY (gift_id) REFERENCES gift (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE gift_user ADD CONSTRAINT FK_7FEE2414A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE friend_request DROP CONSTRAINT FK_F284D94ED442CF4');
        $this->addSql('ALTER TABLE friend_request DROP CONSTRAINT FK_F284D94CD53EDB6');
        $this->addSql('ALTER TABLE gift DROP CONSTRAINT FK_A47C990D7E3C61F9');
        $this->addSql('ALTER TABLE gift_user DROP CONSTRAINT FK_7FEE241497A95A83');
        $this->addSql('ALTER TABLE gift_user DROP CONSTRAINT FK_7FEE2414A76ED395');
        $this->addSql('DROP TABLE friend_request');
        $this->addSql('DROP TABLE gift');
        $this->addSql('DROP TABLE gift_user');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
